added menu parser
gyarana/YK_Delivery_Project pull request #2
Opened 2021-09-08 10:59 UTC by gyarana

2021-09-08 11:15 UTC, pechenini requested changes

2021-09-08 11:15 UTC, pechenini commented on pkg/model/DBrepositories/restarauntsDBRepositories.go
> +package DBrepositories
тут не нужен префикс DB

2021-09-08 11:15 UTC, pechenini commented on pkg/model/DBrepositories/restarauntsDBRepositories.go
> +	} else {
в данном случае можно опустить else

if boolVar {
 return someResult
} 

return someSomeOtherThing


такое прослеживается во многих местах

2021-09-08 11:15 UTC, pechenini commented on parser/restarauntParser.go
> +		fmt.Println("We have some problem with unmarshalling data. Please check it!")
fmt.Println не совсем подходит для логгирования, 

лучше создать логгер как объект и его использовать

2021-09-08 11:15 UTC, pechenini commented on parser/restarauntParser.go
> +func GetAndUnmarshalMenuData(urlItems string,prItems model.RestarauntMenu,idRest int) *model.RestarauntMenu{
в именах методов не должно быть слова And

2021-09-08 11:15 UTC, pechenini commented on pkg/model/DBrepositories/menuDBRepositories.go
> +type MenuDBRepositoryI interface {
DB можно убрать из имени

2021-09-08 11:15 UTC, pechenini commented on parser/restarauntParser.go
> +			go r.MenuParser(items, idRest)
нет ожидания выполнения всех горутин

2021-09-08 11:15 UTC, pechenini commented on pkg/model/DBrepositories/restarauntsDBRepositories.go
> +package DBrepositories
и почему пакет model находится в pkg?

2021-09-10 19:18 UTC, gyarana commented on pkg/model/DBrepositories/restarauntsDBRepositories.go
> +package DBrepositories
поправил

2021-09-10 19:19 UTC, gyarana commented on pkg/model/DBrepositories/restarauntsDBRepositories.go
> +	} else {
поправил

2021-09-10 19:19 UTC, gyarana commented on parser/restarauntParser.go
> +		fmt.Println("We have some problem with unmarshalling data. Please check it!")
пока что добавил logrus, в дальнейшем покдлючу свой логгер

2021-09-10 19:19 UTC, gyarana commented on parser/restarauntParser.go
> +func GetAndUnmarshalMenuData(urlItems string,prItems model.RestarauntMenu,idRest int) *model.RestarauntMenu{
поправил

2021-09-10 19:19 UTC, gyarana commented on pkg/model/DBrepositories/menuDBRepositories.go
> +type MenuDBRepositoryI interface {
поправил

2021-09-10 19:19 UTC, gyarana commented on parser/restarauntParser.go
> +			go r.MenuParser(items, idRest)
поправил

2021-10-11 09:51 UTC, merged